/**
 * Permissions chi tiết cho hệ thống RBAC
 * Format: RESOURCE_ACTION
 */
export enum Permission {
  // User Management
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_LIST = 'USER_LIST',
  USER_MANAGE_ROLES = 'USER_MANAGE_ROLES',

  // Course Management
  COURSE_CREATE = 'COURSE_CREATE',
  COURSE_READ = 'COURSE_READ',
  COURSE_UPDATE = 'COURSE_UPDATE',
  COURSE_DELETE = 'COURSE_DELETE',
  COURSE_LIST = 'COURSE_LIST',
  COURSE_PUBLISH = 'COURSE_PUBLISH',

  // Unit Management
  UNIT_CREATE = 'UNIT_CREATE',
  UNIT_READ = 'UNIT_READ',
  UNIT_UPDATE = 'UNIT_UPDATE',
  UNIT_DELETE = 'UNIT_DELETE',

  // Lesson Management
  LESSON_CREATE = 'LESSON_CREATE',
  LESSON_READ = 'LESSON_READ',
  LESSON_UPDATE = 'LESSON_UPDATE',
  LESSON_DELETE = 'LESSON_DELETE',

  // Exercise Management
  EXERCISE_CREATE = 'EXERCISE_CREATE',
  EXERCISE_READ = 'EXERCISE_READ',
  EXERCISE_UPDATE = 'EXERCISE_UPDATE',
  EXERCISE_DELETE = 'EXERCISE_DELETE',
  EXERCISE_SUBMIT = 'EXERCISE_SUBMIT',

  // Vocabulary Management
  VOCABULARY_CREATE = 'VOCABULARY_CREATE',
  VOCABULARY_READ = 'VOCABULARY_READ',
  VOCABULARY_UPDATE = 'VOCABULARY_UPDATE',
  VOCABULARY_DELETE = 'VOCABULARY_DELETE',

  // Grammar Management
  GRAMMAR_CREATE = 'GRAMMAR_CREATE',
  GRAMMAR_READ = 'GRAMMAR_READ',
  GRAMMAR_UPDATE = 'GRAMMAR_UPDATE',
  GRAMMAR_DELETE = 'GRAMMAR_DELETE',

  // Progress Management
  PROGRESS_READ = 'PROGRESS_READ',
  PROGRESS_UPDATE = 'PROGRESS_UPDATE',
  PROGRESS_DELETE = 'PROGRESS_DELETE',
  PROGRESS_VIEW_ALL = 'PROGRESS_VIEW_ALL',

  // Content Management
  CONTENT_CREATE = 'CONTENT_CREATE',
  CONTENT_READ = 'CONTENT_READ',
  CONTENT_UPDATE = 'CONTENT_UPDATE',
  CONTENT_DELETE = 'CONTENT_DELETE',

  // System Management
  SYSTEM_SETTINGS = 'SYSTEM_SETTINGS',
  SYSTEM_LOGS = 'SYSTEM_LOGS',
  CACHE_MANAGE = 'CACHE_MANAGE',
}
