export enum Permission {
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_LIST = 'USER_LIST',
  USER_MANAGE_ROLES = 'USER_MANAGE_ROLES',

  COURSE_CREATE = 'COURSE_CREATE',
  COURSE_READ = 'COURSE_READ',
  COURSE_UPDATE = 'COURSE_UPDATE',
  COURSE_DELETE = 'COURSE_DELETE',
  COURSE_LIST = 'COURSE_LIST',
  COURSE_PUBLISH = 'COURSE_PUBLISH',

  MODULE_CREATE = 'MODULE_CREATE',
  MODULE_READ = 'MODULE_READ',
  MODULE_UPDATE = 'MODULE_UPDATE',
  MODULE_DELETE = 'MODULE_DELETE',

  LESSON_CREATE = 'LESSON_CREATE',
  LESSON_READ = 'LESSON_READ',
  LESSON_UPDATE = 'LESSON_UPDATE',
  LESSON_DELETE = 'LESSON_DELETE',

  EXERCISE_CREATE = 'EXERCISE_CREATE',
  EXERCISE_READ = 'EXERCISE_READ',
  EXERCISE_UPDATE = 'EXERCISE_UPDATE',
  EXERCISE_DELETE = 'EXERCISE_DELETE',
  EXERCISE_SUBMIT = 'EXERCISE_SUBMIT',

  VOCABULARY_CREATE = 'VOCABULARY_CREATE',
  VOCABULARY_READ = 'VOCABULARY_READ',
  VOCABULARY_UPDATE = 'VOCABULARY_UPDATE',
  VOCABULARY_DELETE = 'VOCABULARY_DELETE',

  GRAMMAR_CREATE = 'GRAMMAR_CREATE',
  GRAMMAR_READ = 'GRAMMAR_READ',
  GRAMMAR_UPDATE = 'GRAMMAR_UPDATE',
  GRAMMAR_DELETE = 'GRAMMAR_DELETE',

  PROGRESS_READ = 'PROGRESS_READ',
  PROGRESS_UPDATE = 'PROGRESS_UPDATE',
  PROGRESS_DELETE = 'PROGRESS_DELETE',
  PROGRESS_VIEW_ALL = 'PROGRESS_VIEW_ALL',

  CONTENT_CREATE = 'CONTENT_CREATE',
  CONTENT_READ = 'CONTENT_READ',
  CONTENT_UPDATE = 'CONTENT_UPDATE',
  CONTENT_DELETE = 'CONTENT_DELETE',

  SYSTEM_SETTINGS = 'SYSTEM_SETTINGS',
  SYSTEM_LOGS = 'SYSTEM_LOGS',
  CACHE_MANAGE = 'CACHE_MANAGE',
  ADMIN_ACCESS = 'ADMIN_ACCESS',
}
